import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const resources = {
  pt: { translation: {
    nav: { property: 'Propriedades', stages: 'Próximas etapas', audiences: 'Para quem', partners: 'Parceiros', technology: 'Tecnologia', registrations: 'Ver inscrições' },
    modal: { label: 'Apresentação institucional', title: 'Este é um ambiente demonstrativo.', text: 'Conteúdos, datas, números e propriedades apresentados são simulações para visualização do projeto Soccez.', close: 'Entendi, continuar' },
    hero: { eyebrow: 'A próxima geração entra em campo', title1: 'Transformamos futebol em', title2: 'propriedades de valor.', text: 'Estratégia, operação e experiência para eventos que conectam atletas, clubes, famílias e grandes marcas.', primary: 'Conheça as próximas etapas', secondary: 'Nossa atuação', stamp: 'Gestão esportiva', stamp2: 'produzida para escalar' },
    manifesto: { eyebrow: 'Muito além do calendário', title1: 'Não organizamos apenas eventos.', title2: 'Construímos ativos esportivos.', text: 'Cada propriedade nasce com identidade, recorrência e visão comercial. Da primeira inscrição ao último conteúdo, tudo faz parte da mesma experiência.', link1: 'Estratégia e gestão', link2: 'Operação e experiência', link3: 'Comercial e marcas' },
    stages: { eyebrow: 'Próximas etapas', title: 'O jogo continua.', text: 'Propriedades que conectam territórios, marcas e formação esportiva.', soon: 'Em breve · Data simulada', ticket: 'Inscrições na TicketEZ', previous: 'Etapa anterior', next: 'Próxima etapa', items: [['Torneio Supermercados BH','Belo Horizonte'],['Torneio Supermercados BH','Vitória'],['Torneio Supermercados BH','Uberaba'],['Etapa Coimbra FC Porto','Contagem'],['Etapa Toca da Raposa','Belo Horizonte']] },
    ticket: { eyebrow: 'Infraestrutura oficial de acesso', title1: 'A jornada começa', title2: 'antes do apito.', text: 'Inscrições, credenciamento e acesso em uma experiência digital fluida, segura e preparada para grandes públicos.', cta: 'Acessar TicketEZ' },
    audiences: { eyebrow: 'Um ecossistema conectado', title: 'Valor para quem faz o jogo acontecer.', athlete: ['Para atletas', 'Mais visibilidade. Mais história.', 'Cada participação fortalece um perfil digital que acompanha a evolução do atleta.'], club: ['Para clubes e escolinhas', 'Um novo canal de crescimento.', 'Calendário competitivo, experiência profissional e novas oportunidades para atletas, famílias e comissões técnicas.'], brand: ['Para marcas', 'Presença que vira experiência.', 'Propriedades recorrentes, ativações relevantes e conexão real com famílias e comunidades.'], more: 'Conheça a solução' },
    business: { eyebrow: 'Soluções B2B', title: 'Modelos diferentes para cada player do futebol.', academyTitle: 'Escolinhas parceiras', academyText: 'Entregamos um calendário qualificado para a base, com operação profissional e uma experiência que gera retenção, receita e valor para as famílias.', academyItems: ['Calendário competitivo recorrente', 'Retenção e novas receitas', 'Histórico digital dos atletas'], academyCta: 'Quero ser escolinha parceira', clubTitle: 'Clubes', clubText: 'Criamos e operamos eventos oficiais dos clubes em capitais e interiores, ampliando a presença da marca, o relacionamento com torcedores e as oportunidades de identificação de atletas.', clubItems: ['Seletivas e propriedades oficiais', 'Fan engagement e expansão territorial', 'Captação de talentos em escala'], clubCta: 'Criar um evento do clube', brandTitle: 'Marcas', brandText: 'Transformamos patrocínio em presença relevante: naming rights, conteúdo, ativações e experiências desenhadas para dialogar com atletas e famílias.', brandItems: ['Propriedades recorrentes e mensuráveis', 'Ativações dentro e fora do campo', 'Conteúdo e relacionamento com comunidades'], brandCta: 'Falar sobre patrocínio' },
    numbers: { eyebrow: 'Impacto projetado', title: 'Escala que pode ser vista, medida e ampliada.', items: [['500 mil+', 'Presença digital'], ['25 mil+', 'Presenças de familiares'], ['3.500+', 'Atletas impactados'], ['10+', 'Selecionados para categorias de base']] },
    tech: { eyebrow: 'Infraestrutura tecnológica do evento', title1: 'DRAFuT + MatchOS.', title2: 'Dados que transformam participação em oportunidade.', text: 'Uma camada integrada para centralizar dados, realizar peneiras remotas, acompanhar jogadores e entregar inteligência esportiva com segurança e conformidade à LGPD.', chips: ['Dados centralizados', 'Peneiras remotas', 'Tracking de jogadores', 'Scouting e relatórios', 'LGPD e segurança'] },
    properties: { eyebrow: 'Produzido pela Soccez', title: 'Um portfólio de propriedades e colaborações.', cupTitle: 'Leandro Guerreiro Cup', cupText: 'Uma propriedade de futebol de base com experiência, formação e conexão — planejada, produzida e desenvolvida pela Soccez.', badge: 'Uma propriedade Soccez', collaboration: 'Colaboração', items: [['Circuito Supermercados BH','Torneios recorrentes de futebol de base'],['Seletivas Cruzeiro','Oportunidades e presença territorial do clube'],['Etapas Coimbra FC Porto','Formação, competição e identificação'],['Copa TicketEZ','Experiência esportiva com acesso digital']] },
    partners: { eyebrow: 'Marcas que jogam com a gente', title: 'Parceiros estratégicos', text: 'Tecnologia, varejo e instituições esportivas conectadas a uma experiência de alto nível.' },
    closing: { eyebrow: 'O próximo grande jogo', title1: 'Sua marca pode fazer', title2: 'parte dessa história.', cta: 'Vamos conversar' },
    footer: { text: 'Gestão, produção e desenvolvimento de propriedades esportivas.', privacy: 'Privacidade', terms: 'Termos' },
    cities: ['Belo Horizonte', 'Vitória', 'Uberaba', 'Contagem', 'Toca da Raposa']
  }},
  en: { translation: {
    nav: { property: 'Properties', stages: 'Upcoming stages', audiences: 'For whom', partners: 'Partners', technology: 'Technology', registrations: 'View registrations' },
    modal: { label: 'Institutional presentation', title: 'This is a demonstration environment.', text: 'The content, dates, figures and properties presented are simulations created to showcase the Soccez project.', close: 'Got it, continue' },
    hero: { eyebrow: 'The next generation steps onto the pitch', title1: 'We turn football into', title2: 'valuable properties.', text: 'Strategy, operations and experiences for events that connect athletes, clubs, families and leading brands.', primary: 'Explore upcoming stages', secondary: 'What we do', stamp: 'Sports management', stamp2: 'built to scale' },
    manifesto: { eyebrow: 'Beyond the calendar', title1: 'We do more than run events.', title2: 'We build sports assets.', text: 'Every property is designed with identity, recurrence and commercial vision. From the first registration to the final piece of content, everything belongs to one experience.', link1: 'Strategy and management', link2: 'Operations and experience', link3: 'Commercial and brands' },
    stages: { eyebrow: 'Upcoming stages', title: 'The game goes on.', text: 'Properties connecting territories, brands and player development.', soon: 'Coming soon · Simulated date', ticket: 'Register on TicketEZ', previous: 'Previous stage', next: 'Next stage', items: [['Supermercados BH Tournament','Belo Horizonte'],['Supermercados BH Tournament','Vitória'],['Supermercados BH Tournament','Uberaba'],['Coimbra FC Porto Stage','Contagem'],['Toca da Raposa Stage','Belo Horizonte']] },
    ticket: { eyebrow: 'Official access infrastructure', title1: 'The journey begins', title2: 'before kick-off.', text: 'Registration, accreditation and access through a seamless, secure digital experience built for large audiences.', cta: 'Visit TicketEZ' },
    audiences: { eyebrow: 'A connected ecosystem', title: 'Value for everyone who makes the game happen.', athlete: ['For athletes', 'More visibility. A lasting journey.', 'Every appearance strengthens a digital profile that follows the athlete’s development.'], club: ['For clubs and academies', 'A new growth channel.', 'Competitive calendars, professional experiences and new opportunities for players, families and coaching staff.'], brand: ['For brands', 'Presence becomes experience.', 'Recurring properties, relevant activations and authentic connections with families and communities.'], more: 'Explore the solution' },
    business: { eyebrow: 'B2B solutions', title: 'Different models for every player in football.', academyTitle: 'Partner academies', academyText: 'We deliver a qualified youth calendar with professional operations and an experience designed to generate retention, revenue and value for families.', academyItems: ['Recurring competitive calendar', 'Retention and new revenue', 'Digital athlete history'], academyCta: 'Become a partner academy', clubTitle: 'Clubs', clubText: 'We create and operate official club events across capitals and regional cities, expanding brand presence, fan relationships and opportunities to identify players.', clubItems: ['Official tryouts and properties', 'Fan engagement and territorial growth', 'Scalable talent identification'], clubCta: 'Create a club event', brandTitle: 'Brands', brandText: 'We turn sponsorship into relevant presence through naming rights, content, activations and experiences designed for athletes and families.', brandItems: ['Recurring, measurable properties', 'On- and off-pitch activations', 'Content and community relationships'], brandCta: 'Discuss sponsorship' },
    numbers: { eyebrow: 'Projected impact', title: 'Scale that can be seen, measured and expanded.', items: [['500K+', 'Digital reach'], ['25K+', 'Family attendance'], ['3,500+', 'Athletes impacted'], ['10+', 'Players selected for academies']] },
    tech: { eyebrow: 'Event technology infrastructure', title1: 'DRAFuT + MatchOS.', title2: 'Data that turns participation into opportunity.', text: 'An integrated layer to centralise data, enable remote tryouts, track players and deliver sports intelligence securely and in compliance with data protection standards.', chips: ['Centralised data', 'Remote tryouts', 'Player tracking', 'Scouting and reports', 'Data privacy and security'] },
    properties: { eyebrow: 'Produced by Soccez', title: 'A portfolio of properties and collaborations.', cupTitle: 'Leandro Guerreiro Cup', cupText: 'A youth football property combining experience, development and connection — planned, produced and developed by Soccez.', badge: 'A Soccez property', collaboration: 'Collaboration', items: [['Supermercados BH Circuit','Recurring youth football tournaments'],['Cruzeiro Tryouts','Opportunities and territorial club presence'],['Coimbra FC Porto Stages','Development, competition and identification'],['TicketEZ Cup','Sports experiences with digital access']] },
    partners: { eyebrow: 'Brands playing alongside us', title: 'Strategic partners', text: 'Technology, retail and sports institutions connected through a high-level experience.' },
    closing: { eyebrow: 'The next big game', title1: 'Your brand can become', title2: 'part of this story.', cta: 'Let’s talk' },
    footer: { text: 'Management, production and development of sports properties.', privacy: 'Privacy', terms: 'Terms' },
    cities: ['Belo Horizonte', 'Vitória', 'Uberaba', 'Contagem', 'Toca da Raposa']
  }}
}

i18n.use(initReactI18next).init({ resources, lng: localStorage.getItem('soccez-language') || 'pt', fallbackLng: 'pt', interpolation: { escapeValue: false } })
i18n.on('languageChanged', language => { localStorage.setItem('soccez-language', language); document.documentElement.lang = language === 'pt' ? 'pt-BR' : 'en' })

export default i18n
